source : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [70]:
import torch 

torch.__version__

'1.12.0+cpu'

In [71]:
torch.cuda.is_available()

False

In [72]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [20]:
scaler = torch.tensor(7)
scaler, scaler.ndim, scaler.item()

(tensor(7), 0, 7)

In [21]:
vector = torch.tensor([7, 7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [32]:
matrix = torch.tensor([[7,8,5],[1,9,1]])
matrix, matrix.shape

(tensor([[7, 8, 5],
         [1, 9, 1]]),
 torch.Size([2, 3]))

In [30]:
matrix[:,2] # like numpy or tensorflow

tensor([5, 1])

In [65]:
torch.manual_seed(42)
tensor = torch.rand(30).reshape(2,5,3)
tensor.ndim, tensor.shape, tensor

(3,
 torch.Size([2, 5, 3]),
 tensor([[[0.8823, 0.9150, 0.3829],
          [0.9593, 0.3904, 0.6009],
          [0.2566, 0.7936, 0.9408],
          [0.1332, 0.9346, 0.5936],
          [0.8694, 0.5677, 0.7411]],
 
         [[0.4294, 0.8854, 0.5739],
          [0.2666, 0.6274, 0.2696],
          [0.4414, 0.2969, 0.8317],
          [0.1053, 0.2695, 0.3588],
          [0.1994, 0.5472, 0.0062]]]))

In [68]:
z = torch.full((4,4),1, dtype=torch.float32)
z

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

> i think most function is same as numpy 